import pandas as pd
import os


if os.path.isfile("config/configfile.yaml"):
    configfile: "config/configfile.yaml"

samples = (
    pd.read_csv(config["samples"], sep="\t", dtype={"sample": str})
    .set_index("sample", drop=False)
    .sort_index()

)

outdir = config["outdir"]
minsize = config["min_contig_length"]

# # Dynamically load all modules/rules
# smks = list(listfiles('rules/core/{section}/{part}.smk'))
#
# for smk,rule in smks:
#     include: smk

include: "rules/common.smk"
include: "rules/preprocessing.smk"
include: "rules/mash_clustering.smk"
include: "rules/coassembly.smk"
include: "rules/single_sample_assembly.smk"
include: "rules/size_filter.smk"
include: "rules/prokaryote-gene_prediction_and_annotation.smk"
include: "rules/euk_gene_prediction.smk"
include: "rules/binning.smk"
include: "rules/mag_linkage.smk"
include: "rules/test_rule.smk"


# # Load report
#for rpt, rule in list(listfiles('workflow/rules/report/{part}.smk')):
#    name = rule
#    include: rpt
#

# Dynamically add all output files
# outfiles = []
# for name,rule in rules.__dict__.items():
#     for file in rule.output:
#         outfiles.append(file)

target = None


if config['assembly_method'] == "coassembly":
    target = expand(f"{config['outdir']}/results/05_test/{{sample_pool}}/{{sample_pool}}_test.txt",
                    sample_pool=samples["sample_pool"].unique())
                    #, sample_name=samples["sample"])
elif config['assembly_method'] == "single_assembly":
    target = expand(f"{config['outdir']}/results/05_test/{{sample}}/{{sample}}_test.txt",
                    sample=samples["sample"])
else:
    raise ValueError("Unsupported assembly type")

rule all:
    input:
        target,
        expand(f"{config['outdir']}/results/05_prokaryote_annotation/MetaPhlAn/{{sample}}.txt", sample=samples["sample"]),
        f"{outdir}/results/05_prokaryote_annotation/MetaPhlAn/merged_abundance_table.tsv"
    # input: expand(output,
    #               sample=config["data"],
    #               treatment=config["treatment"],
    #               assembler=config["assembler"],
    #               binner=config["binner"],
    #               kmers=config["assembly-klist"]
    #              )

