# This config file is used to store the configuration of the Orochi pipeline.
# For each parameter, we've provided a brief description of what it does and an example value. Please modify the values as needed.

# The path to the sample sheet (TSV format) that contains the sample information.
# The sample sheet should contain the following columns: SampleID, Fastq1, Fastq2, Group, and Condition.
samples: "config/samples.tsv"

# The path to the output directory.
outdir: "/scratch/mattiash/OrichTestRun"

# The path to the temporary directory.
tmpdir: "/tmp"

# The default number of threads to use for each rule.
threads: 32

# Max memory to be used by bbmap/bbnorm (I advise using as much as possible). Only change the number between -Xmx and g. E.g. -Xmx1500g, -Xmx400g:
bbmap_mem: '-Xmx100g'

# min_qual: The minimum quality score for trimming.
min_qual: 30

# min_length: The minimum length of the reads after trimming.
min_length: 150

# host_removal: Default: True. If True, host removal will be performed.
host_removal: True

# host_genome: The path to the host genome.
host_genome: "resources/data/reference/beta-vulgaris-subset.fasta"

# host_index: The path to the host genome index.
host_index: "/path/to/host/genome/index"

# bbmap_D: The desired kmer depth for read normalisation @Todo: rename to bbnorm, is more clear.
bbmap_D: 20

# emapper_database: The path to the eggNOG database.
emapper_database: "/path/to/emapper/database"

# emapper_diamond: @Todo: Add description
emapper_diamond: "/path/to/emapper/diamond"

# CAT_database: The path to the CAT database.
CAT_database: "/path/to/CAT/database"

# CAT_taxonomy: The path to the CAT taxonomy files
CAT_taxonomy: "/path/to/CAT/taxonomy"

# min_contig_length: The minimum length of the contigs.
min_contig_length: 1000

# min_contig_antismash: The minimum length of the contigs for antiSMASH analysis.
min_contig_antismash: 5000

# assembly_method: The assembly method to use. Options: single_assembly (spades), coassembly (megahit).
assembly_method: coassembly

# normalize_reads: Whether to use read normalisation: Yes or No
normalize_reads: "Yes"

# sample_pooling: The sample pooling method to use. Options: supervised, unsupervised, no.
sample_pooling: supervised

# clustering: Chosen number of clusters. Only active if UNSUPERVISED sample pooling chosen. Type "0" if number of clusters should be calculated based on data.
clustering: 0

# assembly_threads: The number of threads to use for assembly.
assembly_threads: 32

# assembly_mem: The amount of memory to use for assembly. This is a percentage of max memory. E.g. 0.9, 0.8 etc.
megahit_mem: '0.9'

# kmers: The k-mer sizes to use for assembly.
# @Todo: this is overwritten bij --presets meta-large in megahit. Which is k 27 - 127 with steps of 10. Do something with this.
kmers: "27,37,47,57,67,77,87"

