# This config file is used to store the configuration of the Orochi pipeline.
# For each parameter, we've provided a brief description of what it does and an example value. Please modify the values as needed.

# The path to the sample sheet (TSV format) that contains the sample information.
# The sample sheet should contain the following columns: SampleID, Fastq1, Fastq2, Group, and Condition.
samples: "config/samples.tsv"

# The path to the temporary directory.
tmpdir: /tmp

# The default number of threads to use for each rule.
threads: 32

# min_qual: The minimum quality score for trimming.
min_qual: 30

# min_length: The minimum length of the reads after trimming.
min_length: 150

# host_removal: Default: True. If True, host removal will be performed.
host_removal: True

# host_genome: The path to the host genome.
host_genome: "resources/data/reference/beta-vulgaris-subset.fasta"

# host_index: The path to the host genome index.
host_index: /path/to/host/genome/index

# emapper_database: The path to the eggNOG database.
emapper_database: /path/to/emapper/database

# emapper_diamond: @Todo: Add description
emapper_diamond: /path/to/emapper/diamond

# CAT_database: The path to the CAT database.
CAT_database: /path/to/CAT/database

# CAT_taxonomy: The path to the CAT taxonomy files
CAT_taxonomy: /path/to/CAT/taxonomy

# min_contig_length: The minimum length of the contigs.
min_contig_length: 1000

# min_contig_antismash: The minimum length of the contigs for antiSMASH analysis.
min_contig_antismash: 5000

# assembly_method: The assembly method to use. Options: single assembly (spades), co-assembly (megahit).
assembly_method: single assembly

# sample_pooling: The sample pooling method to use. Options: supervised, unsupervised.
sample_pooling: supervised

# assembly_threads: The number of threads to use for assembly.
assembly_threads: 32

# kmers: The k-mer sizes to use for assembly.
kmers: 21,33,55,77,99,127

